version: '3.9'

services:
      
  site:
    volumes:
      - ./:/site/
      - /var/run/docker.sock:/var/run/docker.sock
      
    image: python:3.10.7
    container_name: site
    
    build:
      context: .
      dockerfile: Dockerfile
      
    working_dir: /site
    restart: unless-stopped
    command: python server.py
    
    ports:
      - "80:80"
      